// Generated by Dagger (https://dagger.dev).
package com.vkpractice.app.data.mappers;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class CommentsMapper_Factory implements Factory<CommentsMapper> {
  @Override
  public CommentsMapper get() {
    return newInstance();
  }

  public static CommentsMapper_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static CommentsMapper newInstance() {
    return new CommentsMapper();
  }

  private static final class InstanceHolder {
    private static final CommentsMapper_Factory INSTANCE = new CommentsMapper_Factory();
  }
}
