// Generated by Dagger (https://dagger.dev).
package com.vkpractice.app.data.mappers;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class PostsMapper_Factory implements Factory<PostsMapper> {
  @Override
  public PostsMapper get() {
    return newInstance();
  }

  public static PostsMapper_Factory create() {
    return InstanceHolder.INSTANCE;
  }

  public static PostsMapper newInstance() {
    return new PostsMapper();
  }

  private static final class InstanceHolder {
    private static final PostsMapper_Factory INSTANCE = new PostsMapper_Factory();
  }
}
